const { Schema, model, default: mongoose } = require('mongoose');

const Property = new Schema({
    propertyType: { type: String, required: true },
    negotiable: { type: Boolean, required: true },
    price: { type: Number, required: true },
    ownerShip: { type: String, required: true },
    propertyAge: { type: Number, required: true },
    propertyApproved: { type: Boolean, required: true },
    propertyDescription: { type: String, required: true },
    bankLoan: { type: Boolean, required: true },
    propertyLength: { type: Number, required: true },
    propertyBreadth: { type: Number, required: true },
    propertyArea: { type: Number, required: true },
    propertyAreaUnit: { type: String, required: true },
    noOfBHK: { type: Number, required: true },
    noOfFloor: { type: Number, required: true },
    Attached: { type: Boolean, required: true },
    westernToilet: { type: Boolean, required: true },
    furnished: { type: Boolean, required: true },
    carParking: { type: Boolean, required: true },
    lift: { type: Boolean, required: true },
    electricity: { type: String, required: true },
    facing: { type: String, required: true },
    name: { type: String, required: true },
    mobile: { type: Number, required: true },
    postedBy: { type: String, required: true },
    saleType: { type: String, required: true },
    featuredPackage: { type: Number, required: true },
    PPDPackage: { type: Number, required: true },
    propertyImage: { type: String, required: true },
    UserEmail: { type: String, required: true },
    city: { type: String, required: true },
    locationArea: { type: String, required: true },
    pincode: { type: Number, required: true },
    address: { type: String, required: true },
    landmark: { type: String, required: true },
    latitude: { type: Number, required: true },
    longitude: { type: String, required: true },
    authorId: { type: mongoose.Schema.Types.ObjectId, required: true },
    postedOn: { type: Date, required: true }
});

module.exports = model('Property', Property);